name: ci

on:
  release:
    types: [created]

env:
  NODE_VERSION: '16.13.2'

jobs:
  evaluate-workspaces:
    name: Evaluate Workspaces
    runs-on: ubuntu-latest
    outputs:
      cache: ${{ steps.store-cache.outputs.result }}
      packages: ${{ steps.store-packages.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
      - name: Store Cache
        id: store-cache
        run: |-
          result=$(yarn config get cacheFolder);
          echo "::set-output name=result::${result}";
          echo "$result";
      - name: Cache Modules
        uses: actions/cache@v3
        with:
          path: ${{ steps.store-cache.outputs.result }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Modules
        run: yarn install --immutable
      - name: Store Packages
        id: store-packages
        run: |-
          result=$( \
            args="--no-private --recursive --since=${{ steps.store-sha.outputs.result }}" \
            yarn run list \
              | jq -c \
          );
          echo "::set-output name=result::${result}";
          echo "$result";

  publish-packages:
    name: Publish Packages
    runs-on: ubuntu-latest
    needs:
      - evaluate-workspaces
    if: ${{ needs.evaluate-workspaces.outputs.packages != '[]' && needs.evaluate-workspaces.outputs.packages != '' }}
    strategy:
      matrix:
        workspace: ${{ fromJSON(needs.evaluate-workspaces.outputs.packages) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
      - name: Cache Modules
        uses: actions/cache@v3
        with:
          path: ${{ needs.evaluate-workspaces.outputs.cache }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Modules
        run: yarn install --immutable
      - name: Publish Packages
        run: yarn workspace ${{ matrix.workspace.name }} npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
