name: ci

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '16.13.2'

jobs:
  publish-packages:
    name: Publish Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
      - name: Store Cache
        id: store-cache
        run: |-
          result=$(yarn config get cacheFolder);
          echo "::set-output name=result::${result}";
          echo "$result";
      - name: Cache Modules
        uses: actions/cache@v3
        with:
          path: ${{ steps.store-cache.outputs.result }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Modules
        run: yarn install --immutable
      - name: Store Last Successful Build
        id: store-sha
        run: |-
          result=$( \
            gh run list \
              --json name,status,conclusion,event,headBranch,headSha \
              --jq '
                map(
                  select(
                    .name == "ci" and
                    .status == "completed" and
                    .conclusion == "success" and
                    .event == "push" and
                    .headBranch == "main"
                  )
                ) | min_by(.createdAt) | .headSha
              '
          );
          echo "::set-output name=result::${result}";
          echo "$result";
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.event.repository.name }}
      - name: Authenticate
        run: yarn config set npmScopes.rahil-p.npmAuthToken '${{secrets.NPM_TOKEN}}'
      - name: Publish Packages
        run: |-
          yarn workspaces foreach \
            --exclude lint-configs \
            --since=${{ steps.store-sha.outputs.result }} \
            --no-private \
            npm publish --access public
