name: ci

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '16.13.2'

  publish-packages:
    name: Publish Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
      - name: Cache Modules
        uses: actions/cache@v3
        with:
          path: ${{ needs.evaluate-workspaces.outputs.cache }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Modules
        run: yarn install --immutable
      - name: Authenticate
        run: yarn config set npmScopes.rahil-p.npmAuthToken '${{secrets.NPM_TOKEN}}'
      - name: Publish Packages
        run: yarn workspaces foreach --exclude lint-configs --since --no-private npm publish --access public
